//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APISigmaSystek.wsSigma7 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsSigma7.WsInt_DevKitSoap")]
    public interface WsInt_DevKitSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ParStrSolicitudes del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DEVKIT_CreacionCasos", ReplyAction="*")]
        APISigmaSystek.wsSigma7.DEVKIT_CreacionCasosResponse DEVKIT_CreacionCasos(APISigmaSystek.wsSigma7.DEVKIT_CreacionCasosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DEVKIT_CreacionCasos", ReplyAction="*")]
        System.Threading.Tasks.Task<APISigmaSystek.wsSigma7.DEVKIT_CreacionCasosResponse> DEVKIT_CreacionCasosAsync(APISigmaSystek.wsSigma7.DEVKIT_CreacionCasosRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ParStrSolicitudes del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DEVKIT_InsUdpParametros", ReplyAction="*")]
        APISigmaSystek.wsSigma7.DEVKIT_InsUdpParametrosResponse DEVKIT_InsUdpParametros(APISigmaSystek.wsSigma7.DEVKIT_InsUdpParametrosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DEVKIT_InsUdpParametros", ReplyAction="*")]
        System.Threading.Tasks.Task<APISigmaSystek.wsSigma7.DEVKIT_InsUdpParametrosResponse> DEVKIT_InsUdpParametrosAsync(APISigmaSystek.wsSigma7.DEVKIT_InsUdpParametrosRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ParStrSolicitudes del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DEVKIT_MoverFlujo", ReplyAction="*")]
        APISigmaSystek.wsSigma7.DEVKIT_MoverFlujoResponse DEVKIT_MoverFlujo(APISigmaSystek.wsSigma7.DEVKIT_MoverFlujoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DEVKIT_MoverFlujo", ReplyAction="*")]
        System.Threading.Tasks.Task<APISigmaSystek.wsSigma7.DEVKIT_MoverFlujoResponse> DEVKIT_MoverFlujoAsync(APISigmaSystek.wsSigma7.DEVKIT_MoverFlujoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ParStrCaso del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DEVKIT_ConsultaCasos", ReplyAction="*")]
        APISigmaSystek.wsSigma7.DEVKIT_ConsultaCasosResponse DEVKIT_ConsultaCasos(APISigmaSystek.wsSigma7.DEVKIT_ConsultaCasosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DEVKIT_ConsultaCasos", ReplyAction="*")]
        System.Threading.Tasks.Task<APISigmaSystek.wsSigma7.DEVKIT_ConsultaCasosResponse> DEVKIT_ConsultaCasosAsync(APISigmaSystek.wsSigma7.DEVKIT_ConsultaCasosRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ParStrCaso del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DEVKIT_ConsultaCasosDet", ReplyAction="*")]
        APISigmaSystek.wsSigma7.DEVKIT_ConsultaCasosDetResponse DEVKIT_ConsultaCasosDet(APISigmaSystek.wsSigma7.DEVKIT_ConsultaCasosDetRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DEVKIT_ConsultaCasosDet", ReplyAction="*")]
        System.Threading.Tasks.Task<APISigmaSystek.wsSigma7.DEVKIT_ConsultaCasosDetResponse> DEVKIT_ConsultaCasosDetAsync(APISigmaSystek.wsSigma7.DEVKIT_ConsultaCasosDetRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DEVKIT_CreacionCasosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DEVKIT_CreacionCasos", Namespace="http://tempuri.org/", Order=0)]
        public APISigmaSystek.wsSigma7.DEVKIT_CreacionCasosRequestBody Body;
        
        public DEVKIT_CreacionCasosRequest() {
        }
        
        public DEVKIT_CreacionCasosRequest(APISigmaSystek.wsSigma7.DEVKIT_CreacionCasosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DEVKIT_CreacionCasosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ParStrSolicitudes;
        
        public DEVKIT_CreacionCasosRequestBody() {
        }
        
        public DEVKIT_CreacionCasosRequestBody(string ParStrSolicitudes) {
            this.ParStrSolicitudes = ParStrSolicitudes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DEVKIT_CreacionCasosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DEVKIT_CreacionCasosResponse", Namespace="http://tempuri.org/", Order=0)]
        public APISigmaSystek.wsSigma7.DEVKIT_CreacionCasosResponseBody Body;
        
        public DEVKIT_CreacionCasosResponse() {
        }
        
        public DEVKIT_CreacionCasosResponse(APISigmaSystek.wsSigma7.DEVKIT_CreacionCasosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DEVKIT_CreacionCasosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DEVKIT_CreacionCasosResult;
        
        public DEVKIT_CreacionCasosResponseBody() {
        }
        
        public DEVKIT_CreacionCasosResponseBody(string DEVKIT_CreacionCasosResult) {
            this.DEVKIT_CreacionCasosResult = DEVKIT_CreacionCasosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DEVKIT_InsUdpParametrosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DEVKIT_InsUdpParametros", Namespace="http://tempuri.org/", Order=0)]
        public APISigmaSystek.wsSigma7.DEVKIT_InsUdpParametrosRequestBody Body;
        
        public DEVKIT_InsUdpParametrosRequest() {
        }
        
        public DEVKIT_InsUdpParametrosRequest(APISigmaSystek.wsSigma7.DEVKIT_InsUdpParametrosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DEVKIT_InsUdpParametrosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ParStrSolicitudes;
        
        public DEVKIT_InsUdpParametrosRequestBody() {
        }
        
        public DEVKIT_InsUdpParametrosRequestBody(string ParStrSolicitudes) {
            this.ParStrSolicitudes = ParStrSolicitudes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DEVKIT_InsUdpParametrosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DEVKIT_InsUdpParametrosResponse", Namespace="http://tempuri.org/", Order=0)]
        public APISigmaSystek.wsSigma7.DEVKIT_InsUdpParametrosResponseBody Body;
        
        public DEVKIT_InsUdpParametrosResponse() {
        }
        
        public DEVKIT_InsUdpParametrosResponse(APISigmaSystek.wsSigma7.DEVKIT_InsUdpParametrosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DEVKIT_InsUdpParametrosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DEVKIT_InsUdpParametrosResult;
        
        public DEVKIT_InsUdpParametrosResponseBody() {
        }
        
        public DEVKIT_InsUdpParametrosResponseBody(string DEVKIT_InsUdpParametrosResult) {
            this.DEVKIT_InsUdpParametrosResult = DEVKIT_InsUdpParametrosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DEVKIT_MoverFlujoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DEVKIT_MoverFlujo", Namespace="http://tempuri.org/", Order=0)]
        public APISigmaSystek.wsSigma7.DEVKIT_MoverFlujoRequestBody Body;
        
        public DEVKIT_MoverFlujoRequest() {
        }
        
        public DEVKIT_MoverFlujoRequest(APISigmaSystek.wsSigma7.DEVKIT_MoverFlujoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DEVKIT_MoverFlujoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ParStrSolicitudes;
        
        public DEVKIT_MoverFlujoRequestBody() {
        }
        
        public DEVKIT_MoverFlujoRequestBody(string ParStrSolicitudes) {
            this.ParStrSolicitudes = ParStrSolicitudes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DEVKIT_MoverFlujoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DEVKIT_MoverFlujoResponse", Namespace="http://tempuri.org/", Order=0)]
        public APISigmaSystek.wsSigma7.DEVKIT_MoverFlujoResponseBody Body;
        
        public DEVKIT_MoverFlujoResponse() {
        }
        
        public DEVKIT_MoverFlujoResponse(APISigmaSystek.wsSigma7.DEVKIT_MoverFlujoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DEVKIT_MoverFlujoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DEVKIT_MoverFlujoResult;
        
        public DEVKIT_MoverFlujoResponseBody() {
        }
        
        public DEVKIT_MoverFlujoResponseBody(string DEVKIT_MoverFlujoResult) {
            this.DEVKIT_MoverFlujoResult = DEVKIT_MoverFlujoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DEVKIT_ConsultaCasosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DEVKIT_ConsultaCasos", Namespace="http://tempuri.org/", Order=0)]
        public APISigmaSystek.wsSigma7.DEVKIT_ConsultaCasosRequestBody Body;
        
        public DEVKIT_ConsultaCasosRequest() {
        }
        
        public DEVKIT_ConsultaCasosRequest(APISigmaSystek.wsSigma7.DEVKIT_ConsultaCasosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DEVKIT_ConsultaCasosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ParStrCaso;
        
        public DEVKIT_ConsultaCasosRequestBody() {
        }
        
        public DEVKIT_ConsultaCasosRequestBody(string ParStrCaso) {
            this.ParStrCaso = ParStrCaso;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DEVKIT_ConsultaCasosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DEVKIT_ConsultaCasosResponse", Namespace="http://tempuri.org/", Order=0)]
        public APISigmaSystek.wsSigma7.DEVKIT_ConsultaCasosResponseBody Body;
        
        public DEVKIT_ConsultaCasosResponse() {
        }
        
        public DEVKIT_ConsultaCasosResponse(APISigmaSystek.wsSigma7.DEVKIT_ConsultaCasosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DEVKIT_ConsultaCasosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DEVKIT_ConsultaCasosResult;
        
        public DEVKIT_ConsultaCasosResponseBody() {
        }
        
        public DEVKIT_ConsultaCasosResponseBody(string DEVKIT_ConsultaCasosResult) {
            this.DEVKIT_ConsultaCasosResult = DEVKIT_ConsultaCasosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DEVKIT_ConsultaCasosDetRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DEVKIT_ConsultaCasosDet", Namespace="http://tempuri.org/", Order=0)]
        public APISigmaSystek.wsSigma7.DEVKIT_ConsultaCasosDetRequestBody Body;
        
        public DEVKIT_ConsultaCasosDetRequest() {
        }
        
        public DEVKIT_ConsultaCasosDetRequest(APISigmaSystek.wsSigma7.DEVKIT_ConsultaCasosDetRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DEVKIT_ConsultaCasosDetRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ParStrCaso;
        
        public DEVKIT_ConsultaCasosDetRequestBody() {
        }
        
        public DEVKIT_ConsultaCasosDetRequestBody(string ParStrCaso) {
            this.ParStrCaso = ParStrCaso;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DEVKIT_ConsultaCasosDetResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DEVKIT_ConsultaCasosDetResponse", Namespace="http://tempuri.org/", Order=0)]
        public APISigmaSystek.wsSigma7.DEVKIT_ConsultaCasosDetResponseBody Body;
        
        public DEVKIT_ConsultaCasosDetResponse() {
        }
        
        public DEVKIT_ConsultaCasosDetResponse(APISigmaSystek.wsSigma7.DEVKIT_ConsultaCasosDetResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DEVKIT_ConsultaCasosDetResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DEVKIT_ConsultaCasosDetResult;
        
        public DEVKIT_ConsultaCasosDetResponseBody() {
        }
        
        public DEVKIT_ConsultaCasosDetResponseBody(string DEVKIT_ConsultaCasosDetResult) {
            this.DEVKIT_ConsultaCasosDetResult = DEVKIT_ConsultaCasosDetResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WsInt_DevKitSoapChannel : APISigmaSystek.wsSigma7.WsInt_DevKitSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WsInt_DevKitSoapClient : System.ServiceModel.ClientBase<APISigmaSystek.wsSigma7.WsInt_DevKitSoap>, APISigmaSystek.wsSigma7.WsInt_DevKitSoap {
        
        public WsInt_DevKitSoapClient() {
        }
        
        public WsInt_DevKitSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WsInt_DevKitSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsInt_DevKitSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsInt_DevKitSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        APISigmaSystek.wsSigma7.DEVKIT_CreacionCasosResponse APISigmaSystek.wsSigma7.WsInt_DevKitSoap.DEVKIT_CreacionCasos(APISigmaSystek.wsSigma7.DEVKIT_CreacionCasosRequest request) {
            return base.Channel.DEVKIT_CreacionCasos(request);
        }
        
        public string DEVKIT_CreacionCasos(string ParStrSolicitudes) {
            APISigmaSystek.wsSigma7.DEVKIT_CreacionCasosRequest inValue = new APISigmaSystek.wsSigma7.DEVKIT_CreacionCasosRequest();
            inValue.Body = new APISigmaSystek.wsSigma7.DEVKIT_CreacionCasosRequestBody();
            inValue.Body.ParStrSolicitudes = ParStrSolicitudes;
            APISigmaSystek.wsSigma7.DEVKIT_CreacionCasosResponse retVal = ((APISigmaSystek.wsSigma7.WsInt_DevKitSoap)(this)).DEVKIT_CreacionCasos(inValue);
            return retVal.Body.DEVKIT_CreacionCasosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<APISigmaSystek.wsSigma7.DEVKIT_CreacionCasosResponse> APISigmaSystek.wsSigma7.WsInt_DevKitSoap.DEVKIT_CreacionCasosAsync(APISigmaSystek.wsSigma7.DEVKIT_CreacionCasosRequest request) {
            return base.Channel.DEVKIT_CreacionCasosAsync(request);
        }
        
        public System.Threading.Tasks.Task<APISigmaSystek.wsSigma7.DEVKIT_CreacionCasosResponse> DEVKIT_CreacionCasosAsync(string ParStrSolicitudes) {
            APISigmaSystek.wsSigma7.DEVKIT_CreacionCasosRequest inValue = new APISigmaSystek.wsSigma7.DEVKIT_CreacionCasosRequest();
            inValue.Body = new APISigmaSystek.wsSigma7.DEVKIT_CreacionCasosRequestBody();
            inValue.Body.ParStrSolicitudes = ParStrSolicitudes;
            return ((APISigmaSystek.wsSigma7.WsInt_DevKitSoap)(this)).DEVKIT_CreacionCasosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        APISigmaSystek.wsSigma7.DEVKIT_InsUdpParametrosResponse APISigmaSystek.wsSigma7.WsInt_DevKitSoap.DEVKIT_InsUdpParametros(APISigmaSystek.wsSigma7.DEVKIT_InsUdpParametrosRequest request) {
            return base.Channel.DEVKIT_InsUdpParametros(request);
        }
        
        public string DEVKIT_InsUdpParametros(string ParStrSolicitudes) {
            APISigmaSystek.wsSigma7.DEVKIT_InsUdpParametrosRequest inValue = new APISigmaSystek.wsSigma7.DEVKIT_InsUdpParametrosRequest();
            inValue.Body = new APISigmaSystek.wsSigma7.DEVKIT_InsUdpParametrosRequestBody();
            inValue.Body.ParStrSolicitudes = ParStrSolicitudes;
            APISigmaSystek.wsSigma7.DEVKIT_InsUdpParametrosResponse retVal = ((APISigmaSystek.wsSigma7.WsInt_DevKitSoap)(this)).DEVKIT_InsUdpParametros(inValue);
            return retVal.Body.DEVKIT_InsUdpParametrosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<APISigmaSystek.wsSigma7.DEVKIT_InsUdpParametrosResponse> APISigmaSystek.wsSigma7.WsInt_DevKitSoap.DEVKIT_InsUdpParametrosAsync(APISigmaSystek.wsSigma7.DEVKIT_InsUdpParametrosRequest request) {
            return base.Channel.DEVKIT_InsUdpParametrosAsync(request);
        }
        
        public System.Threading.Tasks.Task<APISigmaSystek.wsSigma7.DEVKIT_InsUdpParametrosResponse> DEVKIT_InsUdpParametrosAsync(string ParStrSolicitudes) {
            APISigmaSystek.wsSigma7.DEVKIT_InsUdpParametrosRequest inValue = new APISigmaSystek.wsSigma7.DEVKIT_InsUdpParametrosRequest();
            inValue.Body = new APISigmaSystek.wsSigma7.DEVKIT_InsUdpParametrosRequestBody();
            inValue.Body.ParStrSolicitudes = ParStrSolicitudes;
            return ((APISigmaSystek.wsSigma7.WsInt_DevKitSoap)(this)).DEVKIT_InsUdpParametrosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        APISigmaSystek.wsSigma7.DEVKIT_MoverFlujoResponse APISigmaSystek.wsSigma7.WsInt_DevKitSoap.DEVKIT_MoverFlujo(APISigmaSystek.wsSigma7.DEVKIT_MoverFlujoRequest request) {
            return base.Channel.DEVKIT_MoverFlujo(request);
        }
        
        public string DEVKIT_MoverFlujo(string ParStrSolicitudes) {
            APISigmaSystek.wsSigma7.DEVKIT_MoverFlujoRequest inValue = new APISigmaSystek.wsSigma7.DEVKIT_MoverFlujoRequest();
            inValue.Body = new APISigmaSystek.wsSigma7.DEVKIT_MoverFlujoRequestBody();
            inValue.Body.ParStrSolicitudes = ParStrSolicitudes;
            APISigmaSystek.wsSigma7.DEVKIT_MoverFlujoResponse retVal = ((APISigmaSystek.wsSigma7.WsInt_DevKitSoap)(this)).DEVKIT_MoverFlujo(inValue);
            return retVal.Body.DEVKIT_MoverFlujoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<APISigmaSystek.wsSigma7.DEVKIT_MoverFlujoResponse> APISigmaSystek.wsSigma7.WsInt_DevKitSoap.DEVKIT_MoverFlujoAsync(APISigmaSystek.wsSigma7.DEVKIT_MoverFlujoRequest request) {
            return base.Channel.DEVKIT_MoverFlujoAsync(request);
        }
        
        public System.Threading.Tasks.Task<APISigmaSystek.wsSigma7.DEVKIT_MoverFlujoResponse> DEVKIT_MoverFlujoAsync(string ParStrSolicitudes) {
            APISigmaSystek.wsSigma7.DEVKIT_MoverFlujoRequest inValue = new APISigmaSystek.wsSigma7.DEVKIT_MoverFlujoRequest();
            inValue.Body = new APISigmaSystek.wsSigma7.DEVKIT_MoverFlujoRequestBody();
            inValue.Body.ParStrSolicitudes = ParStrSolicitudes;
            return ((APISigmaSystek.wsSigma7.WsInt_DevKitSoap)(this)).DEVKIT_MoverFlujoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        APISigmaSystek.wsSigma7.DEVKIT_ConsultaCasosResponse APISigmaSystek.wsSigma7.WsInt_DevKitSoap.DEVKIT_ConsultaCasos(APISigmaSystek.wsSigma7.DEVKIT_ConsultaCasosRequest request) {
            return base.Channel.DEVKIT_ConsultaCasos(request);
        }
        
        public string DEVKIT_ConsultaCasos(string ParStrCaso) {
            APISigmaSystek.wsSigma7.DEVKIT_ConsultaCasosRequest inValue = new APISigmaSystek.wsSigma7.DEVKIT_ConsultaCasosRequest();
            inValue.Body = new APISigmaSystek.wsSigma7.DEVKIT_ConsultaCasosRequestBody();
            inValue.Body.ParStrCaso = ParStrCaso;
            APISigmaSystek.wsSigma7.DEVKIT_ConsultaCasosResponse retVal = ((APISigmaSystek.wsSigma7.WsInt_DevKitSoap)(this)).DEVKIT_ConsultaCasos(inValue);
            return retVal.Body.DEVKIT_ConsultaCasosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<APISigmaSystek.wsSigma7.DEVKIT_ConsultaCasosResponse> APISigmaSystek.wsSigma7.WsInt_DevKitSoap.DEVKIT_ConsultaCasosAsync(APISigmaSystek.wsSigma7.DEVKIT_ConsultaCasosRequest request) {
            return base.Channel.DEVKIT_ConsultaCasosAsync(request);
        }
        
        public System.Threading.Tasks.Task<APISigmaSystek.wsSigma7.DEVKIT_ConsultaCasosResponse> DEVKIT_ConsultaCasosAsync(string ParStrCaso) {
            APISigmaSystek.wsSigma7.DEVKIT_ConsultaCasosRequest inValue = new APISigmaSystek.wsSigma7.DEVKIT_ConsultaCasosRequest();
            inValue.Body = new APISigmaSystek.wsSigma7.DEVKIT_ConsultaCasosRequestBody();
            inValue.Body.ParStrCaso = ParStrCaso;
            return ((APISigmaSystek.wsSigma7.WsInt_DevKitSoap)(this)).DEVKIT_ConsultaCasosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        APISigmaSystek.wsSigma7.DEVKIT_ConsultaCasosDetResponse APISigmaSystek.wsSigma7.WsInt_DevKitSoap.DEVKIT_ConsultaCasosDet(APISigmaSystek.wsSigma7.DEVKIT_ConsultaCasosDetRequest request) {
            return base.Channel.DEVKIT_ConsultaCasosDet(request);
        }
        
        public string DEVKIT_ConsultaCasosDet(string ParStrCaso) {
            APISigmaSystek.wsSigma7.DEVKIT_ConsultaCasosDetRequest inValue = new APISigmaSystek.wsSigma7.DEVKIT_ConsultaCasosDetRequest();
            inValue.Body = new APISigmaSystek.wsSigma7.DEVKIT_ConsultaCasosDetRequestBody();
            inValue.Body.ParStrCaso = ParStrCaso;
            APISigmaSystek.wsSigma7.DEVKIT_ConsultaCasosDetResponse retVal = ((APISigmaSystek.wsSigma7.WsInt_DevKitSoap)(this)).DEVKIT_ConsultaCasosDet(inValue);
            return retVal.Body.DEVKIT_ConsultaCasosDetResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<APISigmaSystek.wsSigma7.DEVKIT_ConsultaCasosDetResponse> APISigmaSystek.wsSigma7.WsInt_DevKitSoap.DEVKIT_ConsultaCasosDetAsync(APISigmaSystek.wsSigma7.DEVKIT_ConsultaCasosDetRequest request) {
            return base.Channel.DEVKIT_ConsultaCasosDetAsync(request);
        }
        
        public System.Threading.Tasks.Task<APISigmaSystek.wsSigma7.DEVKIT_ConsultaCasosDetResponse> DEVKIT_ConsultaCasosDetAsync(string ParStrCaso) {
            APISigmaSystek.wsSigma7.DEVKIT_ConsultaCasosDetRequest inValue = new APISigmaSystek.wsSigma7.DEVKIT_ConsultaCasosDetRequest();
            inValue.Body = new APISigmaSystek.wsSigma7.DEVKIT_ConsultaCasosDetRequestBody();
            inValue.Body.ParStrCaso = ParStrCaso;
            return ((APISigmaSystek.wsSigma7.WsInt_DevKitSoap)(this)).DEVKIT_ConsultaCasosDetAsync(inValue);
        }
    }
}
